version: '3.9'

services:
  db:
    image: postgres:15
    container_name: collector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collector
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  collector:
    build: .
    container_name: collector_app
    depends_on:
      - db
    environment:
      ProcessingSettings__InputFolder: "/app/input"
      PROCESSING_FOLDER_PATH: /files
      ConnectionStrings__Default: Host=db;Port=5432;Database=Collector;Username=postgres;Password=postgres
      ProcessingSettings__RunMode: "Worker"
    volumes:
      - C:\Collector\Input:/app/input

volumes:
  pgdata: